server:
  port: 8082

spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP connection pool settings
    hikari:
      maximum-pool-size: 25
      minimum-idle: 8
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000
      pool-name: ProductServiceHikariCP
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # Performance optimizations
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # Query optimization
        query:
          plan_cache_max_size: 2048
          in_clause_parameter_padding: true
        # Connection provider settings
        connection:
          provider_disables_autocommit: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

logging:
  level:
    com.ecommerce.product: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always