server:
  port: 8080

spring:
  application:
    name: ecommerce-backend
  
  # Database configurations for different domains
  datasource:
    user:
      url: jdbc:mysql://localhost:3306/ecommerce_users?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: user_service
      password: user_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      # HikariCP connection pool settings
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 300000
        max-lifetime: 1200000
        connection-timeout: 20000
        validation-timeout: 3000
        leak-detection-threshold: 60000
        pool-name: UserServiceHikariCP
    product:
      url: jdbc:mysql://localhost:3306/ecommerce_products?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: product_service
      password: product_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      # HikariCP connection pool settings
      hikari:
        maximum-pool-size: 25
        minimum-idle: 8
        idle-timeout: 300000
        max-lifetime: 1200000
        connection-timeout: 20000
        validation-timeout: 3000
        leak-detection-threshold: 60000
        pool-name: ProductServiceHikariCP
    order:
      url: jdbc:mysql://localhost:3306/ecommerce_orders?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: order_service
      password: order_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      # HikariCP connection pool settings
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 300000
        max-lifetime: 1200000
        connection-timeout: 20000
        validation-timeout: 3000
        leak-detection-threshold: 60000
        pool-name: OrderServiceHikariCP
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # Performance optimizations
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # Query optimization
        query:
          plan_cache_max_size: 2048
          in_clause_parameter_padding: true
        # Connection provider settings
        connection:
          provider_disables_autocommit: true
        # Second level cache (if needed)
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Session configuration
  session:
    store-type: redis
    redis:
      namespace: ecommerce:session
    timeout: 30m
  
  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

# JWT configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# CORS configuration
cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# WebSocket configuration
websocket:
  allowed-origins: http://localhost:4200

# Logging configuration
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ecommerce-backend.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized