server:
  port: 8080

spring:
  application:
    name: ecommerce-backend
  
  # Database configurations for different domains
  datasource:
    user:
      url: jdbc:mysql://localhost:3306/ecommerce_users?useSSL=false&serverTimezone=UTC
      username: user_service
      password: user_password
      driver-class-name: com.mysql.cj.jdbc.Driver
    product:
      url: jdbc:mysql://localhost:3306/ecommerce_products?useSSL=false&serverTimezone=UTC
      username: product_service
      password: product_password
      driver-class-name: com.mysql.cj.jdbc.Driver
    order:
      url: jdbc:mysql://localhost:3306/ecommerce_orders?useSSL=false&serverTimezone=UTC
      username: order_service
      password: order_password
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Session configuration
  session:
    store-type: redis
    redis:
      namespace: ecommerce:session
    timeout: 30m
  
  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

# JWT configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# CORS configuration
cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# WebSocket configuration
websocket:
  allowed-origins: http://localhost:4200

# Logging configuration
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ecommerce-backend.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized